# file: .github/workflows/hexlet-ci-app.yml
name: hexlet-ci-app
on: push
jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v3
      # Устанавливаем Node.js
      - uses: actions/setup-node@v3
      - run: make setup
      - run: make test
      - run: make lint